spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://eva2-spring:evaluacion2@eva-u2-spring.wc1bv2n.mongodb.net/discografica-db?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db
